Add explaination for $BITRISE_GIT_MESSAGE
jiikko/devcenter pull request #1
Opened 2020-11-02 03:14 UTC by jiikko

I will make the pull request to origin after merged.

2020-11-02 04:54 UTC, henteko requested changes
動作確認してないですが、 https://devcenter.bitrise.io/jp/builds/available-environment-variables/ を見る限り `BITRISE_GIT_MESSAGE` はコミットメッセージ、プルリクエストタイトルに対応してるので、`GIT_CLONE_COMMIT_MESSAGE_SUBJECT ` は削除しちゃっていいと思うんですがどうでしょうか？

2020-11-02 05:38 UTC, jiikko commented
`GIT_CLONE_COMMIT_MESSAGE_SUBJECT`の削除、よさそうな感じします!


(ところで、 https://devcenter.bitrise.io/jp/builds/available-environment-variables/ に `$GIT_CLONE_COMMIT_MESSAGE_SUBJECT`の記載がないのはなぜ...)

2020-11-05 01:57 UTC, jiikko commented
@henteko 
`$GIT_CLONE_COMMIT_MESSAGE_SUBJECT` を削除して、 `$BITRISE_GIT_MESSAGE`をのせました。
再レビューおねがいします！

2020-11-05 02:34 UTC, tnj commented on _articles/en/deploy/deploy-apps-to-deploygate-from-bitrise.md
> +| Short Message | Summary of update shown on DeployGate.<br>You can use $BITRISE_GIT_MESSAGE if you want to use the commit message, pull request title, or the message you specified if you triggered t
```suggestion
| Short Message | Summary of update shown on DeployGate.<br>You can use $BITRISE_GIT_MESSAGE if you want to use the commit message, the pull request title, or the message you specified when you triggered the build manually. |
```

後置 if のなかで更に if が重なってて難しくなっちゃってた & when のほうがしっくりきました!

2020-11-05 02:42 UTC, henteko approved these changes
良さそう！ありがとうございます！
英語の方はらいさんのやつで！

2020-11-05 03:43 UTC, jiikko commented
@rai @henteko 
ありがとうございます!!! :bow:

2020-11-05 05:40 UTC, merged